# Generated by Django 5.0.14 on 2026-07-13 05:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_status'),
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('mpesa', 'M-Pesa'), ('bank', 'Bank Transfer'), ('cod', 'Cash on Delivery'), ('card', 'Card'), ('wallet', 'Wallet')], max_length=10),
        ),
        migrations.CreateModel(
            name='PaymentProof',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='payment_proofs/%Y/%m/')),
                ('mpesa_code', models.CharField(blank=True, help_text='M-Pesa transaction code e.g. QEK7XXXXX', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Any additional notes about the payment')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_proofs', to='orders.order')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_proofs', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_proofs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment Proof',
                'ordering': ['-created_at'],
            },
        ),
    ]
