# Generated by Django 5.0.14 on 2026-07-14 10:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_tax_rate', models.DecimalField(decimal_places=2, default=16.0, help_text='Default tax rate as percentage (e.g., 16.0 = 16%)', max_digits=5)),
                ('platform_commission_rate', models.DecimalField(decimal_places=2, default=10.0, help_text='Platform commission percentage on each sale', max_digits=5)),
                ('payment_processing_fee', models.DecimalField(decimal_places=2, default=2.5, help_text='Payment processing fee percentage', max_digits=5)),
                ('free_shipping_threshold', models.DecimalField(decimal_places=2, default=10000.0, help_text='Orders above this amount get free shipping', max_digits=10)),
                ('base_shipping_cost', models.DecimalField(decimal_places=2, default=500.0, help_text='Base shipping cost in KES', max_digits=10)),
                ('auto_release_days', models.PositiveIntegerField(default=7, help_text='Auto-release escrow after N days if no dispute')),
                ('dispute_resolution_days', models.PositiveIntegerField(default=3, help_text='Time to resolve disputes in days')),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('maintenance_message', models.TextField(blank=True)),
                ('allow_new_sellers', models.BooleanField(default=True)),
                ('require_seller_verification', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'System Settings',
                'verbose_name_plural': 'System Settings',
            },
        ),
        migrations.CreateModel(
            name='UserSuspension',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('suspension_type', models.CharField(choices=[('suspended', 'Suspended'), ('banned', 'Banned')], max_length=20)),
                ('reason', models.TextField()),
                ('suspended_at', models.DateTimeField(auto_now_add=True)),
                ('suspended_until', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('appeal_submitted', models.BooleanField(default=False)),
                ('appeal_text', models.TextField(blank=True)),
                ('appeal_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Internal admin notes')),
                ('suspended_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suspensions_issued', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='suspension', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-suspended_at'],
            },
        ),
        migrations.CreateModel(
            name='ContentModerationQueue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content_type', models.CharField(choices=[('product_desc', 'Product Description'), ('product_image', 'Product Image'), ('product_review', 'Product Review'), ('seller_profile', 'Seller Profile')], max_length=20)),
                ('content_id', models.CharField(help_text='UUID/ID of the content being moderated', max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=15)),
                ('rejection_reason', models.TextField(blank=True)),
                ('reviewer_notes', models.TextField(blank=True)),
                ('is_flagged', models.BooleanField(default=False)),
                ('flag_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_reviews', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderation_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='core_conten_status_842daf_idx'), models.Index(fields=['content_type', 'status'], name='core_conten_content_954d31_idx')],
            },
        ),
    ]
