# Generated by Django 5.0.14 on 2026-07-17 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('user_update', 'User Update'), ('password_reset', 'Password Reset'), ('role_change', 'Role Change'), ('permission_change', 'Permission Change'), ('user_suspended', 'User Suspended'), ('user_unsuspended', 'User Unsuspended'), ('system', 'System')], max_length=50),
        ),
    ]
