# Generated by Django 5.0.14 on 2026-07-14 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_seller'),
        ('wallets', '0003_wallettopup_checkout_request_id_wallettopup_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransaction',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_transactions', to='orders.order'),
        ),
    ]
