# Generated by Django 5.1.4 on 2026-07-09 05:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0002_alter_order_status'),
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EscrowTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='KES', max_length=3)),
                ('status', models.CharField(choices=[('funded', 'Funded — Awaiting Shipment'), ('shipped', 'Shipped — Awaiting Buyer Confirmation'), ('delivered', 'Delivered — Pending Release'), ('released', 'Released — Funds Sent to Seller'), ('disputed', 'Disputed — Under Review'), ('refunded', 'Refunded — Funds Returned to Buyer'), ('cancelled', 'Cancelled')], db_index=True, default='funded', max_length=15)),
                ('tracking_number', models.CharField(blank=True, max_length=100)),
                ('courier', models.CharField(blank=True, max_length=100)),
                ('seller_shipped_at', models.DateTimeField(blank=True, null=True)),
                ('release_after', models.DateTimeField(blank=True, help_text='Auto-release funds to seller after this datetime if buyer does not respond.', null=True)),
                ('buyer_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('dispute_reason', models.TextField(blank=True)),
                ('dispute_opened_at', models.DateTimeField(blank=True, null=True)),
                ('dispute_evidence', models.TextField(blank=True, help_text='URLs or descriptions of evidence')),
                ('admin_resolution_notes', models.TextField(blank=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('refunded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escrow_purchases', to=settings.AUTH_USER_MODEL)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='escrow', to='orders.order')),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='escrow', to='payments.payment')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escrow_resolutions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Escrow Transaction',
                'verbose_name_plural': 'Escrow Transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EscrowEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('escrow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='escrow.escrowtransaction')),
            ],
            options={
                'verbose_name': 'Escrow Event',
                'ordering': ['created_at'],
            },
        ),
    ]
