# Generated by Django 5.0.14 on 2026-07-11 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='sms_sent',
            field=models.BooleanField(default=False),
        ),
    ]
