# Generated by Django 5.0.14 on 2026-07-13 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productreview_wishlistitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='fit_feedback',
            field=models.CharField(blank=True, choices=[('true_to_size', 'True to size'), ('runs_small', 'Runs small'), ('runs_large', 'Runs large')], max_length=20),
        ),
        migrations.AddField(
            model_name='productreview',
            name='helpful_votes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productreview',
            name='is_verified_purchase',
            field=models.BooleanField(default=False),
        ),
    ]
